# Pandas 
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd
print(pd.__version__)

2.2.3

### Series

In [3]:
# Series - A pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd 
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
series[0]

np.int64(1)

In [5]:
# Create a series from dictionary
data = {"a": 1, "b": 2, "c": 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

### DataFrame

In [6]:
# Create a dataframe from a dictionary of list
data = {
    "Name": ["Vrudish", "Rohan", "Sohan"],
    "Age": [24, 25, 26],
    "City": ["Nagpur", "Pune", "Kolkata"]
}

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age     City
0  Vrudish   24   Nagpur
1    Rohan   25     Pune
2    Sohan   26  Kolkata
<class 'pandas.core.frame.DataFrame'>

In [7]:
# Create a dataframe from a list of dictionaries
data = [
    {"Name": "Vrudish", "Age": 24, "City": "Nagpur"},
    {"Name": "Rohan", "Age": 25, "City": "Pune"},
    {"Name": "Sohan", "Age": 26, "City": "Kolkata"}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age     City
0  Vrudish   24   Nagpur
1    Rohan   25     Pune
2    Sohan   26  Kolkata
<class 'pandas.core.frame.DataFrame'>

In [8]:
# Create a dataframe by reading a csv file 
df = pd.read_csv("sales_data.csv")
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [10]:
df.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

### Accessing Data From DataFrame

In [11]:
## Accessing columns
df["Product Category"]

0          Electronics
1      Home Appliances
2             Clothing
3                Books
4      Beauty Products
            ...
235    Home Appliances
236           Clothing
237              Books
238    Beauty Products
239             Sports
Name: Product Category, Length: 240, dtype: object

In [12]:
## Accessing rows
df.loc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [15]:
## Accessing Specified element
df.at[2, 'Product Category']

'Clothing'

In [16]:
df.iat[2, 2]

'Clothing'

In [17]:
data = {
    "Name": ["Vrudish", "Rohan", "Sohan"],
    "Age": [24, 25, 26],
    "City": ["Nagpur", "Pune", "Kolkata"]
}

### Data Manipulation with DataFrame

In [18]:
df1 = pd.DataFrame(data)
df1

      Name  Age     City
0  Vrudish   24   Nagpur
1    Rohan   25     Pune
2    Sohan   26  Kolkata

In [20]:
# Adding a column
df1["Salary"] = [500000, 400000, 300000]
df1

      Name  Age     City  Salary
0  Vrudish   24   Nagpur  500000
1    Rohan   25     Pune  400000
2    Sohan   26  Kolkata  300000

In [22]:
# Remove a column
df1.drop("Salary", axis=1, inplace=True)

In [23]:
df1

      Name  Age     City
0  Vrudish   24   Nagpur
1    Rohan   25     Pune
2    Sohan   26  Kolkata

In [25]:
# Remove a row 
df1.drop(2, inplace=True)

In [26]:
df1

      Name  Age    City
0  Vrudish   25  Nagpur
1    Rohan   26    Pune

In [24]:
# Add age to the column
df1["Age"] = df1['Age'] + 1 
df1

      Name  Age     City
0  Vrudish   25   Nagpur
1    Rohan   26     Pune
2    Sohan   27  Kolkata

In [28]:
# Display the data types of each column
df.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [29]:
# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [30]:
# More Info about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    object
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB